server:
  port: 8080

spring:
  application:
    name: bot
  config:
    import: "optional:file:bot/.env[.properties]"

app:
  scrapper:
    base-url: http://localhost:8081
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  message-transport:
    type: KAFKA
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    schema-registry-url: http://localhost:8085
    topic: link-updates
    group-id: link-tracker-bot
    dlq-topic: link-updates.DLQ
    max-retries: 3
    retry-backoff-ms: 1000
